FROM haroldli/xiaoya-tvbox:latest

VOLUME /opt/atv/data/
WORKDIR /opt/atv/

COPY target/dependencies/ ./
COPY target/snapshot-dependencies/ ./
COPY target/spring-boot-loader/ ./
COPY target/application/ ./

EXPOSE 4567 80

ENTRYPOINT ["/entrypoint.sh"]

CMD ["81", "--spring.profiles.active=production,xiaoya"]

